// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagerequestcapture"
)

// UsageRequestCaptureUpdate is the builder for updating UsageRequestCapture entities.
type UsageRequestCaptureUpdate struct {
	config
	hooks    []Hook
	mutation *UsageRequestCaptureMutation
}

// Where appends a list predicates to the UsageRequestCaptureUpdate builder.
func (_u *UsageRequestCaptureUpdate) Where(ps ...predicate.UsageRequestCapture) *UsageRequestCaptureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *UsageRequestCaptureUpdate) SetRequestID(v string) *UsageRequestCaptureUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableRequestID(v *string) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *UsageRequestCaptureUpdate) SetAPIKeyID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableAPIKeyID(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *UsageRequestCaptureUpdate) AddAPIKeyID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *UsageRequestCaptureUpdate) ClearAPIKeyID() *UsageRequestCaptureUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageRequestCaptureUpdate) SetUsageLogID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableUsageLogID(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *UsageRequestCaptureUpdate) AddUsageLogID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *UsageRequestCaptureUpdate) ClearUsageLogID() *UsageRequestCaptureUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UsageRequestCaptureUpdate) SetUserID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableUserID(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UsageRequestCaptureUpdate) AddUserID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UsageRequestCaptureUpdate) ClearUserID() *UsageRequestCaptureUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UsageRequestCaptureUpdate) SetAccountID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableAccountID(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UsageRequestCaptureUpdate) AddAccountID(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *UsageRequestCaptureUpdate) ClearAccountID() *UsageRequestCaptureUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UsageRequestCaptureUpdate) SetProvider(v string) *UsageRequestCaptureUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableProvider(v *string) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *UsageRequestCaptureUpdate) SetModel(v string) *UsageRequestCaptureUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableModel(v *string) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *UsageRequestCaptureUpdate) SetEndpoint(v string) *UsageRequestCaptureUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableEndpoint(v *string) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *UsageRequestCaptureUpdate) SetStream(v bool) *UsageRequestCaptureUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableStream(v *bool) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *UsageRequestCaptureUpdate) SetStatusCode(v int) *UsageRequestCaptureUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableStatusCode(v *int) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *UsageRequestCaptureUpdate) AddStatusCode(v int) *UsageRequestCaptureUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *UsageRequestCaptureUpdate) SetDurationMs(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableDurationMs(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *UsageRequestCaptureUpdate) AddDurationMs(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetRequestBytes sets the "request_bytes" field.
func (_u *UsageRequestCaptureUpdate) SetRequestBytes(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetRequestBytes()
	_u.mutation.SetRequestBytes(v)
	return _u
}

// SetNillableRequestBytes sets the "request_bytes" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableRequestBytes(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetRequestBytes(*v)
	}
	return _u
}

// AddRequestBytes adds value to the "request_bytes" field.
func (_u *UsageRequestCaptureUpdate) AddRequestBytes(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddRequestBytes(v)
	return _u
}

// SetResponseBytes sets the "response_bytes" field.
func (_u *UsageRequestCaptureUpdate) SetResponseBytes(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetResponseBytes()
	_u.mutation.SetResponseBytes(v)
	return _u
}

// SetNillableResponseBytes sets the "response_bytes" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableResponseBytes(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetResponseBytes(*v)
	}
	return _u
}

// AddResponseBytes adds value to the "response_bytes" field.
func (_u *UsageRequestCaptureUpdate) AddResponseBytes(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddResponseBytes(v)
	return _u
}

// SetCompressedBytes sets the "compressed_bytes" field.
func (_u *UsageRequestCaptureUpdate) SetCompressedBytes(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.ResetCompressedBytes()
	_u.mutation.SetCompressedBytes(v)
	return _u
}

// SetNillableCompressedBytes sets the "compressed_bytes" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableCompressedBytes(v *int64) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetCompressedBytes(*v)
	}
	return _u
}

// AddCompressedBytes adds value to the "compressed_bytes" field.
func (_u *UsageRequestCaptureUpdate) AddCompressedBytes(v int64) *UsageRequestCaptureUpdate {
	_u.mutation.AddCompressedBytes(v)
	return _u
}

// SetTruncated sets the "truncated" field.
func (_u *UsageRequestCaptureUpdate) SetTruncated(v bool) *UsageRequestCaptureUpdate {
	_u.mutation.SetTruncated(v)
	return _u
}

// SetNillableTruncated sets the "truncated" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableTruncated(v *bool) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetTruncated(*v)
	}
	return _u
}

// SetTruncateReason sets the "truncate_reason" field.
func (_u *UsageRequestCaptureUpdate) SetTruncateReason(v string) *UsageRequestCaptureUpdate {
	_u.mutation.SetTruncateReason(v)
	return _u
}

// SetNillableTruncateReason sets the "truncate_reason" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableTruncateReason(v *string) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetTruncateReason(*v)
	}
	return _u
}

// ClearTruncateReason clears the value of the "truncate_reason" field.
func (_u *UsageRequestCaptureUpdate) ClearTruncateReason() *UsageRequestCaptureUpdate {
	_u.mutation.ClearTruncateReason()
	return _u
}

// SetCaptureSchemaVersion sets the "capture_schema_version" field.
func (_u *UsageRequestCaptureUpdate) SetCaptureSchemaVersion(v int) *UsageRequestCaptureUpdate {
	_u.mutation.ResetCaptureSchemaVersion()
	_u.mutation.SetCaptureSchemaVersion(v)
	return _u
}

// SetNillableCaptureSchemaVersion sets the "capture_schema_version" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableCaptureSchemaVersion(v *int) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetCaptureSchemaVersion(*v)
	}
	return _u
}

// AddCaptureSchemaVersion adds value to the "capture_schema_version" field.
func (_u *UsageRequestCaptureUpdate) AddCaptureSchemaVersion(v int) *UsageRequestCaptureUpdate {
	_u.mutation.AddCaptureSchemaVersion(v)
	return _u
}

// SetPayloadGzip sets the "payload_gzip" field.
func (_u *UsageRequestCaptureUpdate) SetPayloadGzip(v []byte) *UsageRequestCaptureUpdate {
	_u.mutation.SetPayloadGzip(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UsageRequestCaptureUpdate) SetExpiresAt(v time.Time) *UsageRequestCaptureUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdate) SetNillableExpiresAt(v *time.Time) *UsageRequestCaptureUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UsageRequestCaptureUpdate) ClearExpiresAt() *UsageRequestCaptureUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the UsageRequestCaptureMutation object of the builder.
func (_u *UsageRequestCaptureUpdate) Mutation() *UsageRequestCaptureMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageRequestCaptureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageRequestCaptureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageRequestCaptureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageRequestCaptureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageRequestCaptureUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := usagerequestcapture.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := usagerequestcapture.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := usagerequestcapture.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := usagerequestcapture.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TruncateReason(); ok {
		if err := usagerequestcapture.TruncateReasonValidator(v); err != nil {
			return &ValidationError{Name: "truncate_reason", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.truncate_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageRequestCaptureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagerequestcapture.Table, usagerequestcapture.Columns, sqlgraph.NewFieldSpec(usagerequestcapture.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(usagerequestcapture.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(usagerequestcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(usagerequestcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(usagerequestcapture.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(usagerequestcapture.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usagerequestcapture.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usagerequestcapture.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(usagerequestcapture.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(usagerequestcapture.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(usagerequestcapture.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(usagerequestcapture.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(usagerequestcapture.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(usagerequestcapture.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(usagerequestcapture.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(usagerequestcapture.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(usagerequestcapture.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(usagerequestcapture.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldRequestBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestBytes(); ok {
		_spec.AddField(usagerequestcapture.FieldRequestBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResponseBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldResponseBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResponseBytes(); ok {
		_spec.AddField(usagerequestcapture.FieldResponseBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompressedBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldCompressedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompressedBytes(); ok {
		_spec.AddField(usagerequestcapture.FieldCompressedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Truncated(); ok {
		_spec.SetField(usagerequestcapture.FieldTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TruncateReason(); ok {
		_spec.SetField(usagerequestcapture.FieldTruncateReason, field.TypeString, value)
	}
	if _u.mutation.TruncateReasonCleared() {
		_spec.ClearField(usagerequestcapture.FieldTruncateReason, field.TypeString)
	}
	if value, ok := _u.mutation.CaptureSchemaVersion(); ok {
		_spec.SetField(usagerequestcapture.FieldCaptureSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCaptureSchemaVersion(); ok {
		_spec.AddField(usagerequestcapture.FieldCaptureSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PayloadGzip(); ok {
		_spec.SetField(usagerequestcapture.FieldPayloadGzip, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usagerequestcapture.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usagerequestcapture.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagerequestcapture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageRequestCaptureUpdateOne is the builder for updating a single UsageRequestCapture entity.
type UsageRequestCaptureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageRequestCaptureMutation
}

// SetRequestID sets the "request_id" field.
func (_u *UsageRequestCaptureUpdateOne) SetRequestID(v string) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableRequestID(v *string) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *UsageRequestCaptureUpdateOne) SetAPIKeyID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableAPIKeyID(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *UsageRequestCaptureUpdateOne) AddAPIKeyID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *UsageRequestCaptureUpdateOne) ClearAPIKeyID() *UsageRequestCaptureUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageRequestCaptureUpdateOne) SetUsageLogID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableUsageLogID(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *UsageRequestCaptureUpdateOne) AddUsageLogID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *UsageRequestCaptureUpdateOne) ClearUsageLogID() *UsageRequestCaptureUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UsageRequestCaptureUpdateOne) SetUserID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableUserID(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UsageRequestCaptureUpdateOne) AddUserID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *UsageRequestCaptureUpdateOne) ClearUserID() *UsageRequestCaptureUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UsageRequestCaptureUpdateOne) SetAccountID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableAccountID(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UsageRequestCaptureUpdateOne) AddAccountID(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *UsageRequestCaptureUpdateOne) ClearAccountID() *UsageRequestCaptureUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UsageRequestCaptureUpdateOne) SetProvider(v string) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableProvider(v *string) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *UsageRequestCaptureUpdateOne) SetModel(v string) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableModel(v *string) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *UsageRequestCaptureUpdateOne) SetEndpoint(v string) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableEndpoint(v *string) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *UsageRequestCaptureUpdateOne) SetStream(v bool) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableStream(v *bool) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *UsageRequestCaptureUpdateOne) SetStatusCode(v int) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableStatusCode(v *int) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *UsageRequestCaptureUpdateOne) AddStatusCode(v int) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *UsageRequestCaptureUpdateOne) SetDurationMs(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableDurationMs(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *UsageRequestCaptureUpdateOne) AddDurationMs(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetRequestBytes sets the "request_bytes" field.
func (_u *UsageRequestCaptureUpdateOne) SetRequestBytes(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetRequestBytes()
	_u.mutation.SetRequestBytes(v)
	return _u
}

// SetNillableRequestBytes sets the "request_bytes" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableRequestBytes(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetRequestBytes(*v)
	}
	return _u
}

// AddRequestBytes adds value to the "request_bytes" field.
func (_u *UsageRequestCaptureUpdateOne) AddRequestBytes(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddRequestBytes(v)
	return _u
}

// SetResponseBytes sets the "response_bytes" field.
func (_u *UsageRequestCaptureUpdateOne) SetResponseBytes(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetResponseBytes()
	_u.mutation.SetResponseBytes(v)
	return _u
}

// SetNillableResponseBytes sets the "response_bytes" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableResponseBytes(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetResponseBytes(*v)
	}
	return _u
}

// AddResponseBytes adds value to the "response_bytes" field.
func (_u *UsageRequestCaptureUpdateOne) AddResponseBytes(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddResponseBytes(v)
	return _u
}

// SetCompressedBytes sets the "compressed_bytes" field.
func (_u *UsageRequestCaptureUpdateOne) SetCompressedBytes(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetCompressedBytes()
	_u.mutation.SetCompressedBytes(v)
	return _u
}

// SetNillableCompressedBytes sets the "compressed_bytes" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableCompressedBytes(v *int64) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetCompressedBytes(*v)
	}
	return _u
}

// AddCompressedBytes adds value to the "compressed_bytes" field.
func (_u *UsageRequestCaptureUpdateOne) AddCompressedBytes(v int64) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddCompressedBytes(v)
	return _u
}

// SetTruncated sets the "truncated" field.
func (_u *UsageRequestCaptureUpdateOne) SetTruncated(v bool) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetTruncated(v)
	return _u
}

// SetNillableTruncated sets the "truncated" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableTruncated(v *bool) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetTruncated(*v)
	}
	return _u
}

// SetTruncateReason sets the "truncate_reason" field.
func (_u *UsageRequestCaptureUpdateOne) SetTruncateReason(v string) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetTruncateReason(v)
	return _u
}

// SetNillableTruncateReason sets the "truncate_reason" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableTruncateReason(v *string) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetTruncateReason(*v)
	}
	return _u
}

// ClearTruncateReason clears the value of the "truncate_reason" field.
func (_u *UsageRequestCaptureUpdateOne) ClearTruncateReason() *UsageRequestCaptureUpdateOne {
	_u.mutation.ClearTruncateReason()
	return _u
}

// SetCaptureSchemaVersion sets the "capture_schema_version" field.
func (_u *UsageRequestCaptureUpdateOne) SetCaptureSchemaVersion(v int) *UsageRequestCaptureUpdateOne {
	_u.mutation.ResetCaptureSchemaVersion()
	_u.mutation.SetCaptureSchemaVersion(v)
	return _u
}

// SetNillableCaptureSchemaVersion sets the "capture_schema_version" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableCaptureSchemaVersion(v *int) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetCaptureSchemaVersion(*v)
	}
	return _u
}

// AddCaptureSchemaVersion adds value to the "capture_schema_version" field.
func (_u *UsageRequestCaptureUpdateOne) AddCaptureSchemaVersion(v int) *UsageRequestCaptureUpdateOne {
	_u.mutation.AddCaptureSchemaVersion(v)
	return _u
}

// SetPayloadGzip sets the "payload_gzip" field.
func (_u *UsageRequestCaptureUpdateOne) SetPayloadGzip(v []byte) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetPayloadGzip(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UsageRequestCaptureUpdateOne) SetExpiresAt(v time.Time) *UsageRequestCaptureUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UsageRequestCaptureUpdateOne) SetNillableExpiresAt(v *time.Time) *UsageRequestCaptureUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UsageRequestCaptureUpdateOne) ClearExpiresAt() *UsageRequestCaptureUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the UsageRequestCaptureMutation object of the builder.
func (_u *UsageRequestCaptureUpdateOne) Mutation() *UsageRequestCaptureMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageRequestCaptureUpdate builder.
func (_u *UsageRequestCaptureUpdateOne) Where(ps ...predicate.UsageRequestCapture) *UsageRequestCaptureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageRequestCaptureUpdateOne) Select(field string, fields ...string) *UsageRequestCaptureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageRequestCapture entity.
func (_u *UsageRequestCaptureUpdateOne) Save(ctx context.Context) (*UsageRequestCapture, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageRequestCaptureUpdateOne) SaveX(ctx context.Context) *UsageRequestCapture {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageRequestCaptureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageRequestCaptureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageRequestCaptureUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := usagerequestcapture.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := usagerequestcapture.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := usagerequestcapture.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := usagerequestcapture.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TruncateReason(); ok {
		if err := usagerequestcapture.TruncateReasonValidator(v); err != nil {
			return &ValidationError{Name: "truncate_reason", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.truncate_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageRequestCaptureUpdateOne) sqlSave(ctx context.Context) (_node *UsageRequestCapture, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagerequestcapture.Table, usagerequestcapture.Columns, sqlgraph.NewFieldSpec(usagerequestcapture.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageRequestCapture.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagerequestcapture.FieldID)
		for _, f := range fields {
			if !usagerequestcapture.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagerequestcapture.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(usagerequestcapture.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(usagerequestcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(usagerequestcapture.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(usagerequestcapture.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(usagerequestcapture.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usagerequestcapture.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usagerequestcapture.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(usagerequestcapture.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(usagerequestcapture.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(usagerequestcapture.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(usagerequestcapture.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(usagerequestcapture.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(usagerequestcapture.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(usagerequestcapture.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(usagerequestcapture.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(usagerequestcapture.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(usagerequestcapture.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(usagerequestcapture.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldRequestBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestBytes(); ok {
		_spec.AddField(usagerequestcapture.FieldRequestBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResponseBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldResponseBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResponseBytes(); ok {
		_spec.AddField(usagerequestcapture.FieldResponseBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompressedBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldCompressedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompressedBytes(); ok {
		_spec.AddField(usagerequestcapture.FieldCompressedBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Truncated(); ok {
		_spec.SetField(usagerequestcapture.FieldTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TruncateReason(); ok {
		_spec.SetField(usagerequestcapture.FieldTruncateReason, field.TypeString, value)
	}
	if _u.mutation.TruncateReasonCleared() {
		_spec.ClearField(usagerequestcapture.FieldTruncateReason, field.TypeString)
	}
	if value, ok := _u.mutation.CaptureSchemaVersion(); ok {
		_spec.SetField(usagerequestcapture.FieldCaptureSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCaptureSchemaVersion(); ok {
		_spec.AddField(usagerequestcapture.FieldCaptureSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PayloadGzip(); ok {
		_spec.SetField(usagerequestcapture.FieldPayloadGzip, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usagerequestcapture.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usagerequestcapture.FieldExpiresAt, field.TypeTime)
	}
	_node = &UsageRequestCapture{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagerequestcapture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
