// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagerequestcaptureshare"
)

// UsageRequestCaptureShareUpdate is the builder for updating UsageRequestCaptureShare entities.
type UsageRequestCaptureShareUpdate struct {
	config
	hooks    []Hook
	mutation *UsageRequestCaptureShareMutation
}

// Where appends a list predicates to the UsageRequestCaptureShareUpdate builder.
func (_u *UsageRequestCaptureShareUpdate) Where(ps ...predicate.UsageRequestCaptureShare) *UsageRequestCaptureShareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShareID sets the "share_id" field.
func (_u *UsageRequestCaptureShareUpdate) SetShareID(v string) *UsageRequestCaptureShareUpdate {
	_u.mutation.SetShareID(v)
	return _u
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableShareID(v *string) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetShareID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *UsageRequestCaptureShareUpdate) SetRequestID(v string) *UsageRequestCaptureShareUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableRequestID(v *string) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *UsageRequestCaptureShareUpdate) SetAPIKeyID(v int64) *UsageRequestCaptureShareUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableAPIKeyID(v *int64) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *UsageRequestCaptureShareUpdate) AddAPIKeyID(v int64) *UsageRequestCaptureShareUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *UsageRequestCaptureShareUpdate) ClearAPIKeyID() *UsageRequestCaptureShareUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UsageRequestCaptureShareUpdate) SetCreatedBy(v int64) *UsageRequestCaptureShareUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableCreatedBy(v *int64) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UsageRequestCaptureShareUpdate) AddCreatedBy(v int64) *UsageRequestCaptureShareUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *UsageRequestCaptureShareUpdate) ClearCreatedBy() *UsageRequestCaptureShareUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetLabel sets the "label" field.
func (_u *UsageRequestCaptureShareUpdate) SetLabel(v string) *UsageRequestCaptureShareUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableLabel(v *string) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *UsageRequestCaptureShareUpdate) ClearLabel() *UsageRequestCaptureShareUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UsageRequestCaptureShareUpdate) SetExpiresAt(v time.Time) *UsageRequestCaptureShareUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableExpiresAt(v *time.Time) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UsageRequestCaptureShareUpdate) ClearExpiresAt() *UsageRequestCaptureShareUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *UsageRequestCaptureShareUpdate) SetRevokedAt(v time.Time) *UsageRequestCaptureShareUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableRevokedAt(v *time.Time) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *UsageRequestCaptureShareUpdate) ClearRevokedAt() *UsageRequestCaptureShareUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *UsageRequestCaptureShareUpdate) SetViewCount(v int) *UsageRequestCaptureShareUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableViewCount(v *int) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *UsageRequestCaptureShareUpdate) AddViewCount(v int) *UsageRequestCaptureShareUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (_u *UsageRequestCaptureShareUpdate) SetLastViewedAt(v time.Time) *UsageRequestCaptureShareUpdate {
	_u.mutation.SetLastViewedAt(v)
	return _u
}

// SetNillableLastViewedAt sets the "last_viewed_at" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdate) SetNillableLastViewedAt(v *time.Time) *UsageRequestCaptureShareUpdate {
	if v != nil {
		_u.SetLastViewedAt(*v)
	}
	return _u
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (_u *UsageRequestCaptureShareUpdate) ClearLastViewedAt() *UsageRequestCaptureShareUpdate {
	_u.mutation.ClearLastViewedAt()
	return _u
}

// Mutation returns the UsageRequestCaptureShareMutation object of the builder.
func (_u *UsageRequestCaptureShareUpdate) Mutation() *UsageRequestCaptureShareMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageRequestCaptureShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageRequestCaptureShareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageRequestCaptureShareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageRequestCaptureShareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageRequestCaptureShareUpdate) check() error {
	if v, ok := _u.mutation.ShareID(); ok {
		if err := usagerequestcaptureshare.ShareIDValidator(v); err != nil {
			return &ValidationError{Name: "share_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.share_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := usagerequestcaptureshare.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := usagerequestcaptureshare.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.label": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageRequestCaptureShareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagerequestcaptureshare.Table, usagerequestcaptureshare.Columns, sqlgraph.NewFieldSpec(usagerequestcaptureshare.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShareID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldShareID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(usagerequestcaptureshare.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(usagerequestcaptureshare.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(usagerequestcaptureshare.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastViewedAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldLastViewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastViewedAtCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldLastViewedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagerequestcaptureshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageRequestCaptureShareUpdateOne is the builder for updating a single UsageRequestCaptureShare entity.
type UsageRequestCaptureShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageRequestCaptureShareMutation
}

// SetShareID sets the "share_id" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetShareID(v string) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.SetShareID(v)
	return _u
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableShareID(v *string) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetShareID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetRequestID(v string) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableRequestID(v *string) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetAPIKeyID(v int64) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableAPIKeyID(v *int64) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *UsageRequestCaptureShareUpdateOne) AddAPIKeyID(v int64) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *UsageRequestCaptureShareUpdateOne) ClearAPIKeyID() *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetCreatedBy(v int64) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableCreatedBy(v *int64) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UsageRequestCaptureShareUpdateOne) AddCreatedBy(v int64) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *UsageRequestCaptureShareUpdateOne) ClearCreatedBy() *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetLabel sets the "label" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetLabel(v string) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableLabel(v *string) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *UsageRequestCaptureShareUpdateOne) ClearLabel() *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetExpiresAt(v time.Time) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableExpiresAt(v *time.Time) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UsageRequestCaptureShareUpdateOne) ClearExpiresAt() *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetRevokedAt(v time.Time) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableRevokedAt(v *time.Time) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *UsageRequestCaptureShareUpdateOne) ClearRevokedAt() *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetViewCount(v int) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableViewCount(v *int) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *UsageRequestCaptureShareUpdateOne) AddViewCount(v int) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (_u *UsageRequestCaptureShareUpdateOne) SetLastViewedAt(v time.Time) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.SetLastViewedAt(v)
	return _u
}

// SetNillableLastViewedAt sets the "last_viewed_at" field if the given value is not nil.
func (_u *UsageRequestCaptureShareUpdateOne) SetNillableLastViewedAt(v *time.Time) *UsageRequestCaptureShareUpdateOne {
	if v != nil {
		_u.SetLastViewedAt(*v)
	}
	return _u
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (_u *UsageRequestCaptureShareUpdateOne) ClearLastViewedAt() *UsageRequestCaptureShareUpdateOne {
	_u.mutation.ClearLastViewedAt()
	return _u
}

// Mutation returns the UsageRequestCaptureShareMutation object of the builder.
func (_u *UsageRequestCaptureShareUpdateOne) Mutation() *UsageRequestCaptureShareMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageRequestCaptureShareUpdate builder.
func (_u *UsageRequestCaptureShareUpdateOne) Where(ps ...predicate.UsageRequestCaptureShare) *UsageRequestCaptureShareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageRequestCaptureShareUpdateOne) Select(field string, fields ...string) *UsageRequestCaptureShareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageRequestCaptureShare entity.
func (_u *UsageRequestCaptureShareUpdateOne) Save(ctx context.Context) (*UsageRequestCaptureShare, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageRequestCaptureShareUpdateOne) SaveX(ctx context.Context) *UsageRequestCaptureShare {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageRequestCaptureShareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageRequestCaptureShareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageRequestCaptureShareUpdateOne) check() error {
	if v, ok := _u.mutation.ShareID(); ok {
		if err := usagerequestcaptureshare.ShareIDValidator(v); err != nil {
			return &ValidationError{Name: "share_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.share_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := usagerequestcaptureshare.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := usagerequestcaptureshare.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.label": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageRequestCaptureShareUpdateOne) sqlSave(ctx context.Context) (_node *UsageRequestCaptureShare, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagerequestcaptureshare.Table, usagerequestcaptureshare.Columns, sqlgraph.NewFieldSpec(usagerequestcaptureshare.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageRequestCaptureShare.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagerequestcaptureshare.FieldID)
		for _, f := range fields {
			if !usagerequestcaptureshare.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagerequestcaptureshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShareID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldShareID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(usagerequestcaptureshare.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(usagerequestcaptureshare.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(usagerequestcaptureshare.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastViewedAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldLastViewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastViewedAtCleared() {
		_spec.ClearField(usagerequestcaptureshare.FieldLastViewedAt, field.TypeTime)
	}
	_node = &UsageRequestCaptureShare{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagerequestcaptureshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
