// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagerequestcapture"
)

// UsageRequestCapture is the model entity for the UsageRequestCapture schema.
type UsageRequestCapture struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode int `json:"status_code,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// RequestBytes holds the value of the "request_bytes" field.
	RequestBytes int64 `json:"request_bytes,omitempty"`
	// ResponseBytes holds the value of the "response_bytes" field.
	ResponseBytes int64 `json:"response_bytes,omitempty"`
	// CompressedBytes holds the value of the "compressed_bytes" field.
	CompressedBytes int64 `json:"compressed_bytes,omitempty"`
	// Truncated holds the value of the "truncated" field.
	Truncated bool `json:"truncated,omitempty"`
	// TruncateReason holds the value of the "truncate_reason" field.
	TruncateReason *string `json:"truncate_reason,omitempty"`
	// CaptureSchemaVersion holds the value of the "capture_schema_version" field.
	CaptureSchemaVersion int `json:"capture_schema_version,omitempty"`
	// PayloadGzip holds the value of the "payload_gzip" field.
	PayloadGzip []byte `json:"payload_gzip,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageRequestCapture) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagerequestcapture.FieldPayloadGzip:
			values[i] = new([]byte)
		case usagerequestcapture.FieldStream, usagerequestcapture.FieldTruncated:
			values[i] = new(sql.NullBool)
		case usagerequestcapture.FieldID, usagerequestcapture.FieldAPIKeyID, usagerequestcapture.FieldUsageLogID, usagerequestcapture.FieldUserID, usagerequestcapture.FieldAccountID, usagerequestcapture.FieldStatusCode, usagerequestcapture.FieldDurationMs, usagerequestcapture.FieldRequestBytes, usagerequestcapture.FieldResponseBytes, usagerequestcapture.FieldCompressedBytes, usagerequestcapture.FieldCaptureSchemaVersion:
			values[i] = new(sql.NullInt64)
		case usagerequestcapture.FieldRequestID, usagerequestcapture.FieldProvider, usagerequestcapture.FieldModel, usagerequestcapture.FieldEndpoint, usagerequestcapture.FieldTruncateReason:
			values[i] = new(sql.NullString)
		case usagerequestcapture.FieldCreatedAt, usagerequestcapture.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageRequestCapture fields.
func (_m *UsageRequestCapture) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagerequestcapture.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagerequestcapture.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case usagerequestcapture.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case usagerequestcapture.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case usagerequestcapture.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case usagerequestcapture.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case usagerequestcapture.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case usagerequestcapture.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case usagerequestcapture.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case usagerequestcapture.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case usagerequestcapture.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = int(value.Int64)
			}
		case usagerequestcapture.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		case usagerequestcapture.FieldRequestBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_bytes", values[i])
			} else if value.Valid {
				_m.RequestBytes = value.Int64
			}
		case usagerequestcapture.FieldResponseBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_bytes", values[i])
			} else if value.Valid {
				_m.ResponseBytes = value.Int64
			}
		case usagerequestcapture.FieldCompressedBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field compressed_bytes", values[i])
			} else if value.Valid {
				_m.CompressedBytes = value.Int64
			}
		case usagerequestcapture.FieldTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field truncated", values[i])
			} else if value.Valid {
				_m.Truncated = value.Bool
			}
		case usagerequestcapture.FieldTruncateReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field truncate_reason", values[i])
			} else if value.Valid {
				_m.TruncateReason = new(string)
				*_m.TruncateReason = value.String
			}
		case usagerequestcapture.FieldCaptureSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field capture_schema_version", values[i])
			} else if value.Valid {
				_m.CaptureSchemaVersion = int(value.Int64)
			}
		case usagerequestcapture.FieldPayloadGzip:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload_gzip", values[i])
			} else if value != nil {
				_m.PayloadGzip = *value
			}
		case usagerequestcapture.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagerequestcapture.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageRequestCapture.
// This includes values selected through modifiers, order, etc.
func (_m *UsageRequestCapture) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UsageRequestCapture.
// Note that you need to call UsageRequestCapture.Unwrap() before calling this method if this UsageRequestCapture
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageRequestCapture) Update() *UsageRequestCaptureUpdateOne {
	return NewUsageRequestCaptureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageRequestCapture entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageRequestCapture) Unwrap() *UsageRequestCapture {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageRequestCapture is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageRequestCapture) String() string {
	var builder strings.Builder
	builder.WriteString("UsageRequestCapture(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("request_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBytes))
	builder.WriteString(", ")
	builder.WriteString("response_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBytes))
	builder.WriteString(", ")
	builder.WriteString("compressed_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompressedBytes))
	builder.WriteString(", ")
	builder.WriteString("truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.Truncated))
	builder.WriteString(", ")
	if v := _m.TruncateReason; v != nil {
		builder.WriteString("truncate_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("capture_schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.CaptureSchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("payload_gzip=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadGzip))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UsageRequestCaptures is a parsable slice of UsageRequestCapture.
type UsageRequestCaptures []*UsageRequestCapture
