// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagerequestcaptureshare"
)

// UsageRequestCaptureShare is the model entity for the UsageRequestCaptureShare schema.
type UsageRequestCaptureShare struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ShareID holds the value of the "share_id" field.
	ShareID string `json:"share_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// Label holds the value of the "label" field.
	Label *string `json:"label,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// ViewCount holds the value of the "view_count" field.
	ViewCount int `json:"view_count,omitempty"`
	// LastViewedAt holds the value of the "last_viewed_at" field.
	LastViewedAt *time.Time `json:"last_viewed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageRequestCaptureShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagerequestcaptureshare.FieldID, usagerequestcaptureshare.FieldAPIKeyID, usagerequestcaptureshare.FieldCreatedBy, usagerequestcaptureshare.FieldViewCount:
			values[i] = new(sql.NullInt64)
		case usagerequestcaptureshare.FieldShareID, usagerequestcaptureshare.FieldRequestID, usagerequestcaptureshare.FieldLabel:
			values[i] = new(sql.NullString)
		case usagerequestcaptureshare.FieldExpiresAt, usagerequestcaptureshare.FieldRevokedAt, usagerequestcaptureshare.FieldLastViewedAt, usagerequestcaptureshare.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageRequestCaptureShare fields.
func (_m *UsageRequestCaptureShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagerequestcaptureshare.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagerequestcaptureshare.FieldShareID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field share_id", values[i])
			} else if value.Valid {
				_m.ShareID = value.String
			}
		case usagerequestcaptureshare.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case usagerequestcaptureshare.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case usagerequestcaptureshare.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case usagerequestcaptureshare.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = new(string)
				*_m.Label = value.String
			}
		case usagerequestcaptureshare.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case usagerequestcaptureshare.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case usagerequestcaptureshare.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = int(value.Int64)
			}
		case usagerequestcaptureshare.FieldLastViewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_viewed_at", values[i])
			} else if value.Valid {
				_m.LastViewedAt = new(time.Time)
				*_m.LastViewedAt = value.Time
			}
		case usagerequestcaptureshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageRequestCaptureShare.
// This includes values selected through modifiers, order, etc.
func (_m *UsageRequestCaptureShare) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UsageRequestCaptureShare.
// Note that you need to call UsageRequestCaptureShare.Unwrap() before calling this method if this UsageRequestCaptureShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageRequestCaptureShare) Update() *UsageRequestCaptureShareUpdateOne {
	return NewUsageRequestCaptureShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageRequestCaptureShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageRequestCaptureShare) Unwrap() *UsageRequestCaptureShare {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageRequestCaptureShare is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageRequestCaptureShare) String() string {
	var builder strings.Builder
	builder.WriteString("UsageRequestCaptureShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("share_id=")
	builder.WriteString(_m.ShareID)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Label; v != nil {
		builder.WriteString("label=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteString(", ")
	if v := _m.LastViewedAt; v != nil {
		builder.WriteString("last_viewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageRequestCaptureShares is a parsable slice of UsageRequestCaptureShare.
type UsageRequestCaptureShares []*UsageRequestCaptureShare
