// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagerequestcapture"
)

// UsageRequestCaptureCreate is the builder for creating a UsageRequestCapture entity.
type UsageRequestCaptureCreate struct {
	config
	mutation *UsageRequestCaptureMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *UsageRequestCaptureCreate) SetRequestID(v string) *UsageRequestCaptureCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *UsageRequestCaptureCreate) SetAPIKeyID(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableAPIKeyID(v *int64) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *UsageRequestCaptureCreate) SetUsageLogID(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableUsageLogID(v *int64) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UsageRequestCaptureCreate) SetUserID(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableUserID(v *int64) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UsageRequestCaptureCreate) SetAccountID(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableAccountID(v *int64) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UsageRequestCaptureCreate) SetProvider(v string) *UsageRequestCaptureCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *UsageRequestCaptureCreate) SetModel(v string) *UsageRequestCaptureCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *UsageRequestCaptureCreate) SetEndpoint(v string) *UsageRequestCaptureCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetStream sets the "stream" field.
func (_c *UsageRequestCaptureCreate) SetStream(v bool) *UsageRequestCaptureCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableStream(v *bool) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *UsageRequestCaptureCreate) SetStatusCode(v int) *UsageRequestCaptureCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *UsageRequestCaptureCreate) SetDurationMs(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetRequestBytes sets the "request_bytes" field.
func (_c *UsageRequestCaptureCreate) SetRequestBytes(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetRequestBytes(v)
	return _c
}

// SetResponseBytes sets the "response_bytes" field.
func (_c *UsageRequestCaptureCreate) SetResponseBytes(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetResponseBytes(v)
	return _c
}

// SetCompressedBytes sets the "compressed_bytes" field.
func (_c *UsageRequestCaptureCreate) SetCompressedBytes(v int64) *UsageRequestCaptureCreate {
	_c.mutation.SetCompressedBytes(v)
	return _c
}

// SetTruncated sets the "truncated" field.
func (_c *UsageRequestCaptureCreate) SetTruncated(v bool) *UsageRequestCaptureCreate {
	_c.mutation.SetTruncated(v)
	return _c
}

// SetNillableTruncated sets the "truncated" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableTruncated(v *bool) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetTruncated(*v)
	}
	return _c
}

// SetTruncateReason sets the "truncate_reason" field.
func (_c *UsageRequestCaptureCreate) SetTruncateReason(v string) *UsageRequestCaptureCreate {
	_c.mutation.SetTruncateReason(v)
	return _c
}

// SetNillableTruncateReason sets the "truncate_reason" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableTruncateReason(v *string) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetTruncateReason(*v)
	}
	return _c
}

// SetCaptureSchemaVersion sets the "capture_schema_version" field.
func (_c *UsageRequestCaptureCreate) SetCaptureSchemaVersion(v int) *UsageRequestCaptureCreate {
	_c.mutation.SetCaptureSchemaVersion(v)
	return _c
}

// SetNillableCaptureSchemaVersion sets the "capture_schema_version" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableCaptureSchemaVersion(v *int) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetCaptureSchemaVersion(*v)
	}
	return _c
}

// SetPayloadGzip sets the "payload_gzip" field.
func (_c *UsageRequestCaptureCreate) SetPayloadGzip(v []byte) *UsageRequestCaptureCreate {
	_c.mutation.SetPayloadGzip(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageRequestCaptureCreate) SetCreatedAt(v time.Time) *UsageRequestCaptureCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableCreatedAt(v *time.Time) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UsageRequestCaptureCreate) SetExpiresAt(v time.Time) *UsageRequestCaptureCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UsageRequestCaptureCreate) SetNillableExpiresAt(v *time.Time) *UsageRequestCaptureCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the UsageRequestCaptureMutation object of the builder.
func (_c *UsageRequestCaptureCreate) Mutation() *UsageRequestCaptureMutation {
	return _c.mutation
}

// Save creates the UsageRequestCapture in the database.
func (_c *UsageRequestCaptureCreate) Save(ctx context.Context) (*UsageRequestCapture, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageRequestCaptureCreate) SaveX(ctx context.Context) *UsageRequestCapture {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageRequestCaptureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageRequestCaptureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageRequestCaptureCreate) defaults() {
	if _, ok := _c.mutation.Stream(); !ok {
		v := usagerequestcapture.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.Truncated(); !ok {
		v := usagerequestcapture.DefaultTruncated
		_c.mutation.SetTruncated(v)
	}
	if _, ok := _c.mutation.CaptureSchemaVersion(); !ok {
		v := usagerequestcapture.DefaultCaptureSchemaVersion
		_c.mutation.SetCaptureSchemaVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagerequestcapture.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageRequestCaptureCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "UsageRequestCapture.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := usagerequestcapture.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UsageRequestCapture.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := usagerequestcapture.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UsageRequestCapture.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := usagerequestcapture.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "UsageRequestCapture.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := usagerequestcapture.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "UsageRequestCapture.stream"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "UsageRequestCapture.status_code"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "UsageRequestCapture.duration_ms"`)}
	}
	if _, ok := _c.mutation.RequestBytes(); !ok {
		return &ValidationError{Name: "request_bytes", err: errors.New(`ent: missing required field "UsageRequestCapture.request_bytes"`)}
	}
	if _, ok := _c.mutation.ResponseBytes(); !ok {
		return &ValidationError{Name: "response_bytes", err: errors.New(`ent: missing required field "UsageRequestCapture.response_bytes"`)}
	}
	if _, ok := _c.mutation.CompressedBytes(); !ok {
		return &ValidationError{Name: "compressed_bytes", err: errors.New(`ent: missing required field "UsageRequestCapture.compressed_bytes"`)}
	}
	if _, ok := _c.mutation.Truncated(); !ok {
		return &ValidationError{Name: "truncated", err: errors.New(`ent: missing required field "UsageRequestCapture.truncated"`)}
	}
	if v, ok := _c.mutation.TruncateReason(); ok {
		if err := usagerequestcapture.TruncateReasonValidator(v); err != nil {
			return &ValidationError{Name: "truncate_reason", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCapture.truncate_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CaptureSchemaVersion(); !ok {
		return &ValidationError{Name: "capture_schema_version", err: errors.New(`ent: missing required field "UsageRequestCapture.capture_schema_version"`)}
	}
	if _, ok := _c.mutation.PayloadGzip(); !ok {
		return &ValidationError{Name: "payload_gzip", err: errors.New(`ent: missing required field "UsageRequestCapture.payload_gzip"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageRequestCapture.created_at"`)}
	}
	return nil
}

func (_c *UsageRequestCaptureCreate) sqlSave(ctx context.Context) (*UsageRequestCapture, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageRequestCaptureCreate) createSpec() (*UsageRequestCapture, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageRequestCapture{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagerequestcapture.Table, sqlgraph.NewFieldSpec(usagerequestcapture.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(usagerequestcapture.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(usagerequestcapture.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(usagerequestcapture.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usagerequestcapture.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(usagerequestcapture.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(usagerequestcapture.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(usagerequestcapture.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(usagerequestcapture.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(usagerequestcapture.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(usagerequestcapture.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(usagerequestcapture.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.RequestBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldRequestBytes, field.TypeInt64, value)
		_node.RequestBytes = value
	}
	if value, ok := _c.mutation.ResponseBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldResponseBytes, field.TypeInt64, value)
		_node.ResponseBytes = value
	}
	if value, ok := _c.mutation.CompressedBytes(); ok {
		_spec.SetField(usagerequestcapture.FieldCompressedBytes, field.TypeInt64, value)
		_node.CompressedBytes = value
	}
	if value, ok := _c.mutation.Truncated(); ok {
		_spec.SetField(usagerequestcapture.FieldTruncated, field.TypeBool, value)
		_node.Truncated = value
	}
	if value, ok := _c.mutation.TruncateReason(); ok {
		_spec.SetField(usagerequestcapture.FieldTruncateReason, field.TypeString, value)
		_node.TruncateReason = &value
	}
	if value, ok := _c.mutation.CaptureSchemaVersion(); ok {
		_spec.SetField(usagerequestcapture.FieldCaptureSchemaVersion, field.TypeInt, value)
		_node.CaptureSchemaVersion = value
	}
	if value, ok := _c.mutation.PayloadGzip(); ok {
		_spec.SetField(usagerequestcapture.FieldPayloadGzip, field.TypeBytes, value)
		_node.PayloadGzip = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagerequestcapture.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usagerequestcapture.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageRequestCapture.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageRequestCaptureUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageRequestCaptureCreate) OnConflict(opts ...sql.ConflictOption) *UsageRequestCaptureUpsertOne {
	_c.conflict = opts
	return &UsageRequestCaptureUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageRequestCapture.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageRequestCaptureCreate) OnConflictColumns(columns ...string) *UsageRequestCaptureUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageRequestCaptureUpsertOne{
		create: _c,
	}
}

type (
	// UsageRequestCaptureUpsertOne is the builder for "upsert"-ing
	//  one UsageRequestCapture node.
	UsageRequestCaptureUpsertOne struct {
		create *UsageRequestCaptureCreate
	}

	// UsageRequestCaptureUpsert is the "OnConflict" setter.
	UsageRequestCaptureUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *UsageRequestCaptureUpsert) SetRequestID(v string) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateRequestID() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldRequestID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageRequestCaptureUpsert) SetAPIKeyID(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateAPIKeyID() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageRequestCaptureUpsert) AddAPIKeyID(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *UsageRequestCaptureUpsert) ClearAPIKeyID() *UsageRequestCaptureUpsert {
	u.SetNull(usagerequestcapture.FieldAPIKeyID)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageRequestCaptureUpsert) SetUsageLogID(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateUsageLogID() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *UsageRequestCaptureUpsert) AddUsageLogID(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *UsageRequestCaptureUpsert) ClearUsageLogID() *UsageRequestCaptureUpsert {
	u.SetNull(usagerequestcapture.FieldUsageLogID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UsageRequestCaptureUpsert) SetUserID(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateUserID() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UsageRequestCaptureUpsert) AddUserID(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *UsageRequestCaptureUpsert) ClearUserID() *UsageRequestCaptureUpsert {
	u.SetNull(usagerequestcapture.FieldUserID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UsageRequestCaptureUpsert) SetAccountID(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateAccountID() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageRequestCaptureUpsert) AddAccountID(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageRequestCaptureUpsert) ClearAccountID() *UsageRequestCaptureUpsert {
	u.SetNull(usagerequestcapture.FieldAccountID)
	return u
}

// SetProvider sets the "provider" field.
func (u *UsageRequestCaptureUpsert) SetProvider(v string) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateProvider() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *UsageRequestCaptureUpsert) SetModel(v string) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateModel() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldModel)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *UsageRequestCaptureUpsert) SetEndpoint(v string) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateEndpoint() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldEndpoint)
	return u
}

// SetStream sets the "stream" field.
func (u *UsageRequestCaptureUpsert) SetStream(v bool) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateStream() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldStream)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *UsageRequestCaptureUpsert) SetStatusCode(v int) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateStatusCode() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *UsageRequestCaptureUpsert) AddStatusCode(v int) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldStatusCode, v)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *UsageRequestCaptureUpsert) SetDurationMs(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateDurationMs() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *UsageRequestCaptureUpsert) AddDurationMs(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldDurationMs, v)
	return u
}

// SetRequestBytes sets the "request_bytes" field.
func (u *UsageRequestCaptureUpsert) SetRequestBytes(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldRequestBytes, v)
	return u
}

// UpdateRequestBytes sets the "request_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateRequestBytes() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldRequestBytes)
	return u
}

// AddRequestBytes adds v to the "request_bytes" field.
func (u *UsageRequestCaptureUpsert) AddRequestBytes(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldRequestBytes, v)
	return u
}

// SetResponseBytes sets the "response_bytes" field.
func (u *UsageRequestCaptureUpsert) SetResponseBytes(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldResponseBytes, v)
	return u
}

// UpdateResponseBytes sets the "response_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateResponseBytes() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldResponseBytes)
	return u
}

// AddResponseBytes adds v to the "response_bytes" field.
func (u *UsageRequestCaptureUpsert) AddResponseBytes(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldResponseBytes, v)
	return u
}

// SetCompressedBytes sets the "compressed_bytes" field.
func (u *UsageRequestCaptureUpsert) SetCompressedBytes(v int64) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldCompressedBytes, v)
	return u
}

// UpdateCompressedBytes sets the "compressed_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateCompressedBytes() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldCompressedBytes)
	return u
}

// AddCompressedBytes adds v to the "compressed_bytes" field.
func (u *UsageRequestCaptureUpsert) AddCompressedBytes(v int64) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldCompressedBytes, v)
	return u
}

// SetTruncated sets the "truncated" field.
func (u *UsageRequestCaptureUpsert) SetTruncated(v bool) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldTruncated, v)
	return u
}

// UpdateTruncated sets the "truncated" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateTruncated() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldTruncated)
	return u
}

// SetTruncateReason sets the "truncate_reason" field.
func (u *UsageRequestCaptureUpsert) SetTruncateReason(v string) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldTruncateReason, v)
	return u
}

// UpdateTruncateReason sets the "truncate_reason" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateTruncateReason() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldTruncateReason)
	return u
}

// ClearTruncateReason clears the value of the "truncate_reason" field.
func (u *UsageRequestCaptureUpsert) ClearTruncateReason() *UsageRequestCaptureUpsert {
	u.SetNull(usagerequestcapture.FieldTruncateReason)
	return u
}

// SetCaptureSchemaVersion sets the "capture_schema_version" field.
func (u *UsageRequestCaptureUpsert) SetCaptureSchemaVersion(v int) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldCaptureSchemaVersion, v)
	return u
}

// UpdateCaptureSchemaVersion sets the "capture_schema_version" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateCaptureSchemaVersion() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldCaptureSchemaVersion)
	return u
}

// AddCaptureSchemaVersion adds v to the "capture_schema_version" field.
func (u *UsageRequestCaptureUpsert) AddCaptureSchemaVersion(v int) *UsageRequestCaptureUpsert {
	u.Add(usagerequestcapture.FieldCaptureSchemaVersion, v)
	return u
}

// SetPayloadGzip sets the "payload_gzip" field.
func (u *UsageRequestCaptureUpsert) SetPayloadGzip(v []byte) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldPayloadGzip, v)
	return u
}

// UpdatePayloadGzip sets the "payload_gzip" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdatePayloadGzip() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldPayloadGzip)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UsageRequestCaptureUpsert) SetExpiresAt(v time.Time) *UsageRequestCaptureUpsert {
	u.Set(usagerequestcapture.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsert) UpdateExpiresAt() *UsageRequestCaptureUpsert {
	u.SetExcluded(usagerequestcapture.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UsageRequestCaptureUpsert) ClearExpiresAt() *UsageRequestCaptureUpsert {
	u.SetNull(usagerequestcapture.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageRequestCapture.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageRequestCaptureUpsertOne) UpdateNewValues() *UsageRequestCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagerequestcapture.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageRequestCapture.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageRequestCaptureUpsertOne) Ignore() *UsageRequestCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageRequestCaptureUpsertOne) DoNothing() *UsageRequestCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageRequestCaptureCreate.OnConflict
// documentation for more info.
func (u *UsageRequestCaptureUpsertOne) Update(set func(*UsageRequestCaptureUpsert)) *UsageRequestCaptureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageRequestCaptureUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageRequestCaptureUpsertOne) SetRequestID(v string) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateRequestID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageRequestCaptureUpsertOne) SetAPIKeyID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageRequestCaptureUpsertOne) AddAPIKeyID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateAPIKeyID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *UsageRequestCaptureUpsertOne) ClearAPIKeyID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageRequestCaptureUpsertOne) SetUsageLogID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *UsageRequestCaptureUpsertOne) AddUsageLogID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateUsageLogID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *UsageRequestCaptureUpsertOne) ClearUsageLogID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearUsageLogID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UsageRequestCaptureUpsertOne) SetUserID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UsageRequestCaptureUpsertOne) AddUserID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateUserID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *UsageRequestCaptureUpsertOne) ClearUserID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageRequestCaptureUpsertOne) SetAccountID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageRequestCaptureUpsertOne) AddAccountID(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateAccountID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageRequestCaptureUpsertOne) ClearAccountID() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *UsageRequestCaptureUpsertOne) SetProvider(v string) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateProvider() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *UsageRequestCaptureUpsertOne) SetModel(v string) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateModel() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateModel()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *UsageRequestCaptureUpsertOne) SetEndpoint(v string) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateEndpoint() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateEndpoint()
	})
}

// SetStream sets the "stream" field.
func (u *UsageRequestCaptureUpsertOne) SetStream(v bool) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateStream() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateStream()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *UsageRequestCaptureUpsertOne) SetStatusCode(v int) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *UsageRequestCaptureUpsertOne) AddStatusCode(v int) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateStatusCode() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *UsageRequestCaptureUpsertOne) SetDurationMs(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *UsageRequestCaptureUpsertOne) AddDurationMs(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateDurationMs() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateDurationMs()
	})
}

// SetRequestBytes sets the "request_bytes" field.
func (u *UsageRequestCaptureUpsertOne) SetRequestBytes(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetRequestBytes(v)
	})
}

// AddRequestBytes adds v to the "request_bytes" field.
func (u *UsageRequestCaptureUpsertOne) AddRequestBytes(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddRequestBytes(v)
	})
}

// UpdateRequestBytes sets the "request_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateRequestBytes() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateRequestBytes()
	})
}

// SetResponseBytes sets the "response_bytes" field.
func (u *UsageRequestCaptureUpsertOne) SetResponseBytes(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetResponseBytes(v)
	})
}

// AddResponseBytes adds v to the "response_bytes" field.
func (u *UsageRequestCaptureUpsertOne) AddResponseBytes(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddResponseBytes(v)
	})
}

// UpdateResponseBytes sets the "response_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateResponseBytes() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateResponseBytes()
	})
}

// SetCompressedBytes sets the "compressed_bytes" field.
func (u *UsageRequestCaptureUpsertOne) SetCompressedBytes(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetCompressedBytes(v)
	})
}

// AddCompressedBytes adds v to the "compressed_bytes" field.
func (u *UsageRequestCaptureUpsertOne) AddCompressedBytes(v int64) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddCompressedBytes(v)
	})
}

// UpdateCompressedBytes sets the "compressed_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateCompressedBytes() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateCompressedBytes()
	})
}

// SetTruncated sets the "truncated" field.
func (u *UsageRequestCaptureUpsertOne) SetTruncated(v bool) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetTruncated(v)
	})
}

// UpdateTruncated sets the "truncated" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateTruncated() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateTruncated()
	})
}

// SetTruncateReason sets the "truncate_reason" field.
func (u *UsageRequestCaptureUpsertOne) SetTruncateReason(v string) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetTruncateReason(v)
	})
}

// UpdateTruncateReason sets the "truncate_reason" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateTruncateReason() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateTruncateReason()
	})
}

// ClearTruncateReason clears the value of the "truncate_reason" field.
func (u *UsageRequestCaptureUpsertOne) ClearTruncateReason() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearTruncateReason()
	})
}

// SetCaptureSchemaVersion sets the "capture_schema_version" field.
func (u *UsageRequestCaptureUpsertOne) SetCaptureSchemaVersion(v int) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetCaptureSchemaVersion(v)
	})
}

// AddCaptureSchemaVersion adds v to the "capture_schema_version" field.
func (u *UsageRequestCaptureUpsertOne) AddCaptureSchemaVersion(v int) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddCaptureSchemaVersion(v)
	})
}

// UpdateCaptureSchemaVersion sets the "capture_schema_version" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateCaptureSchemaVersion() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateCaptureSchemaVersion()
	})
}

// SetPayloadGzip sets the "payload_gzip" field.
func (u *UsageRequestCaptureUpsertOne) SetPayloadGzip(v []byte) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetPayloadGzip(v)
	})
}

// UpdatePayloadGzip sets the "payload_gzip" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdatePayloadGzip() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdatePayloadGzip()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UsageRequestCaptureUpsertOne) SetExpiresAt(v time.Time) *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertOne) UpdateExpiresAt() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UsageRequestCaptureUpsertOne) ClearExpiresAt() *UsageRequestCaptureUpsertOne {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *UsageRequestCaptureUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageRequestCaptureCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageRequestCaptureUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageRequestCaptureUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageRequestCaptureUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageRequestCaptureCreateBulk is the builder for creating many UsageRequestCapture entities in bulk.
type UsageRequestCaptureCreateBulk struct {
	config
	err      error
	builders []*UsageRequestCaptureCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageRequestCapture entities in the database.
func (_c *UsageRequestCaptureCreateBulk) Save(ctx context.Context) ([]*UsageRequestCapture, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageRequestCapture, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageRequestCaptureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageRequestCaptureCreateBulk) SaveX(ctx context.Context) []*UsageRequestCapture {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageRequestCaptureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageRequestCaptureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageRequestCapture.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageRequestCaptureUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageRequestCaptureCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageRequestCaptureUpsertBulk {
	_c.conflict = opts
	return &UsageRequestCaptureUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageRequestCapture.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageRequestCaptureCreateBulk) OnConflictColumns(columns ...string) *UsageRequestCaptureUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageRequestCaptureUpsertBulk{
		create: _c,
	}
}

// UsageRequestCaptureUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageRequestCapture nodes.
type UsageRequestCaptureUpsertBulk struct {
	create *UsageRequestCaptureCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageRequestCapture.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageRequestCaptureUpsertBulk) UpdateNewValues() *UsageRequestCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagerequestcapture.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageRequestCapture.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageRequestCaptureUpsertBulk) Ignore() *UsageRequestCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageRequestCaptureUpsertBulk) DoNothing() *UsageRequestCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageRequestCaptureCreateBulk.OnConflict
// documentation for more info.
func (u *UsageRequestCaptureUpsertBulk) Update(set func(*UsageRequestCaptureUpsert)) *UsageRequestCaptureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageRequestCaptureUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageRequestCaptureUpsertBulk) SetRequestID(v string) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateRequestID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageRequestCaptureUpsertBulk) SetAPIKeyID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageRequestCaptureUpsertBulk) AddAPIKeyID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateAPIKeyID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *UsageRequestCaptureUpsertBulk) ClearAPIKeyID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageRequestCaptureUpsertBulk) SetUsageLogID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *UsageRequestCaptureUpsertBulk) AddUsageLogID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateUsageLogID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *UsageRequestCaptureUpsertBulk) ClearUsageLogID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearUsageLogID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UsageRequestCaptureUpsertBulk) SetUserID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UsageRequestCaptureUpsertBulk) AddUserID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateUserID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *UsageRequestCaptureUpsertBulk) ClearUserID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageRequestCaptureUpsertBulk) SetAccountID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageRequestCaptureUpsertBulk) AddAccountID(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateAccountID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageRequestCaptureUpsertBulk) ClearAccountID() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *UsageRequestCaptureUpsertBulk) SetProvider(v string) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateProvider() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *UsageRequestCaptureUpsertBulk) SetModel(v string) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateModel() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateModel()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *UsageRequestCaptureUpsertBulk) SetEndpoint(v string) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateEndpoint() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateEndpoint()
	})
}

// SetStream sets the "stream" field.
func (u *UsageRequestCaptureUpsertBulk) SetStream(v bool) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateStream() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateStream()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *UsageRequestCaptureUpsertBulk) SetStatusCode(v int) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *UsageRequestCaptureUpsertBulk) AddStatusCode(v int) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateStatusCode() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *UsageRequestCaptureUpsertBulk) SetDurationMs(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *UsageRequestCaptureUpsertBulk) AddDurationMs(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateDurationMs() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateDurationMs()
	})
}

// SetRequestBytes sets the "request_bytes" field.
func (u *UsageRequestCaptureUpsertBulk) SetRequestBytes(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetRequestBytes(v)
	})
}

// AddRequestBytes adds v to the "request_bytes" field.
func (u *UsageRequestCaptureUpsertBulk) AddRequestBytes(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddRequestBytes(v)
	})
}

// UpdateRequestBytes sets the "request_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateRequestBytes() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateRequestBytes()
	})
}

// SetResponseBytes sets the "response_bytes" field.
func (u *UsageRequestCaptureUpsertBulk) SetResponseBytes(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetResponseBytes(v)
	})
}

// AddResponseBytes adds v to the "response_bytes" field.
func (u *UsageRequestCaptureUpsertBulk) AddResponseBytes(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddResponseBytes(v)
	})
}

// UpdateResponseBytes sets the "response_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateResponseBytes() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateResponseBytes()
	})
}

// SetCompressedBytes sets the "compressed_bytes" field.
func (u *UsageRequestCaptureUpsertBulk) SetCompressedBytes(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetCompressedBytes(v)
	})
}

// AddCompressedBytes adds v to the "compressed_bytes" field.
func (u *UsageRequestCaptureUpsertBulk) AddCompressedBytes(v int64) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddCompressedBytes(v)
	})
}

// UpdateCompressedBytes sets the "compressed_bytes" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateCompressedBytes() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateCompressedBytes()
	})
}

// SetTruncated sets the "truncated" field.
func (u *UsageRequestCaptureUpsertBulk) SetTruncated(v bool) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetTruncated(v)
	})
}

// UpdateTruncated sets the "truncated" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateTruncated() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateTruncated()
	})
}

// SetTruncateReason sets the "truncate_reason" field.
func (u *UsageRequestCaptureUpsertBulk) SetTruncateReason(v string) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetTruncateReason(v)
	})
}

// UpdateTruncateReason sets the "truncate_reason" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateTruncateReason() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateTruncateReason()
	})
}

// ClearTruncateReason clears the value of the "truncate_reason" field.
func (u *UsageRequestCaptureUpsertBulk) ClearTruncateReason() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearTruncateReason()
	})
}

// SetCaptureSchemaVersion sets the "capture_schema_version" field.
func (u *UsageRequestCaptureUpsertBulk) SetCaptureSchemaVersion(v int) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetCaptureSchemaVersion(v)
	})
}

// AddCaptureSchemaVersion adds v to the "capture_schema_version" field.
func (u *UsageRequestCaptureUpsertBulk) AddCaptureSchemaVersion(v int) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.AddCaptureSchemaVersion(v)
	})
}

// UpdateCaptureSchemaVersion sets the "capture_schema_version" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateCaptureSchemaVersion() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateCaptureSchemaVersion()
	})
}

// SetPayloadGzip sets the "payload_gzip" field.
func (u *UsageRequestCaptureUpsertBulk) SetPayloadGzip(v []byte) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetPayloadGzip(v)
	})
}

// UpdatePayloadGzip sets the "payload_gzip" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdatePayloadGzip() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdatePayloadGzip()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UsageRequestCaptureUpsertBulk) SetExpiresAt(v time.Time) *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UsageRequestCaptureUpsertBulk) UpdateExpiresAt() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UsageRequestCaptureUpsertBulk) ClearExpiresAt() *UsageRequestCaptureUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *UsageRequestCaptureUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageRequestCaptureCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageRequestCaptureCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageRequestCaptureUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
