// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagerequestcaptureshare"
)

// UsageRequestCaptureShareCreate is the builder for creating a UsageRequestCaptureShare entity.
type UsageRequestCaptureShareCreate struct {
	config
	mutation *UsageRequestCaptureShareMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetShareID sets the "share_id" field.
func (_c *UsageRequestCaptureShareCreate) SetShareID(v string) *UsageRequestCaptureShareCreate {
	_c.mutation.SetShareID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *UsageRequestCaptureShareCreate) SetRequestID(v string) *UsageRequestCaptureShareCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *UsageRequestCaptureShareCreate) SetAPIKeyID(v int64) *UsageRequestCaptureShareCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableAPIKeyID(v *int64) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *UsageRequestCaptureShareCreate) SetCreatedBy(v int64) *UsageRequestCaptureShareCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableCreatedBy(v *int64) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *UsageRequestCaptureShareCreate) SetLabel(v string) *UsageRequestCaptureShareCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableLabel(v *string) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UsageRequestCaptureShareCreate) SetExpiresAt(v time.Time) *UsageRequestCaptureShareCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableExpiresAt(v *time.Time) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *UsageRequestCaptureShareCreate) SetRevokedAt(v time.Time) *UsageRequestCaptureShareCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableRevokedAt(v *time.Time) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *UsageRequestCaptureShareCreate) SetViewCount(v int) *UsageRequestCaptureShareCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableViewCount(v *int) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (_c *UsageRequestCaptureShareCreate) SetLastViewedAt(v time.Time) *UsageRequestCaptureShareCreate {
	_c.mutation.SetLastViewedAt(v)
	return _c
}

// SetNillableLastViewedAt sets the "last_viewed_at" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableLastViewedAt(v *time.Time) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetLastViewedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageRequestCaptureShareCreate) SetCreatedAt(v time.Time) *UsageRequestCaptureShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageRequestCaptureShareCreate) SetNillableCreatedAt(v *time.Time) *UsageRequestCaptureShareCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the UsageRequestCaptureShareMutation object of the builder.
func (_c *UsageRequestCaptureShareCreate) Mutation() *UsageRequestCaptureShareMutation {
	return _c.mutation
}

// Save creates the UsageRequestCaptureShare in the database.
func (_c *UsageRequestCaptureShareCreate) Save(ctx context.Context) (*UsageRequestCaptureShare, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageRequestCaptureShareCreate) SaveX(ctx context.Context) *UsageRequestCaptureShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageRequestCaptureShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageRequestCaptureShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageRequestCaptureShareCreate) defaults() {
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := usagerequestcaptureshare.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagerequestcaptureshare.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageRequestCaptureShareCreate) check() error {
	if _, ok := _c.mutation.ShareID(); !ok {
		return &ValidationError{Name: "share_id", err: errors.New(`ent: missing required field "UsageRequestCaptureShare.share_id"`)}
	}
	if v, ok := _c.mutation.ShareID(); ok {
		if err := usagerequestcaptureshare.ShareIDValidator(v); err != nil {
			return &ValidationError{Name: "share_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.share_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "UsageRequestCaptureShare.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := usagerequestcaptureshare.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := usagerequestcaptureshare.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "UsageRequestCaptureShare.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "UsageRequestCaptureShare.view_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageRequestCaptureShare.created_at"`)}
	}
	return nil
}

func (_c *UsageRequestCaptureShareCreate) sqlSave(ctx context.Context) (*UsageRequestCaptureShare, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageRequestCaptureShareCreate) createSpec() (*UsageRequestCaptureShare, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageRequestCaptureShare{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagerequestcaptureshare.Table, sqlgraph.NewFieldSpec(usagerequestcaptureshare.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ShareID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldShareID, field.TypeString, value)
		_node.ShareID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldLabel, field.TypeString, value)
		_node.Label = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.LastViewedAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldLastViewedAt, field.TypeTime, value)
		_node.LastViewedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagerequestcaptureshare.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageRequestCaptureShare.Create().
//		SetShareID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageRequestCaptureShareUpsert) {
//			SetShareID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageRequestCaptureShareCreate) OnConflict(opts ...sql.ConflictOption) *UsageRequestCaptureShareUpsertOne {
	_c.conflict = opts
	return &UsageRequestCaptureShareUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageRequestCaptureShare.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageRequestCaptureShareCreate) OnConflictColumns(columns ...string) *UsageRequestCaptureShareUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageRequestCaptureShareUpsertOne{
		create: _c,
	}
}

type (
	// UsageRequestCaptureShareUpsertOne is the builder for "upsert"-ing
	//  one UsageRequestCaptureShare node.
	UsageRequestCaptureShareUpsertOne struct {
		create *UsageRequestCaptureShareCreate
	}

	// UsageRequestCaptureShareUpsert is the "OnConflict" setter.
	UsageRequestCaptureShareUpsert struct {
		*sql.UpdateSet
	}
)

// SetShareID sets the "share_id" field.
func (u *UsageRequestCaptureShareUpsert) SetShareID(v string) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldShareID, v)
	return u
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateShareID() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldShareID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageRequestCaptureShareUpsert) SetRequestID(v string) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateRequestID() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldRequestID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsert) SetAPIKeyID(v int64) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateAPIKeyID() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsert) AddAPIKeyID(v int64) *UsageRequestCaptureShareUpsert {
	u.Add(usagerequestcaptureshare.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsert) ClearAPIKeyID() *UsageRequestCaptureShareUpsert {
	u.SetNull(usagerequestcaptureshare.FieldAPIKeyID)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *UsageRequestCaptureShareUpsert) SetCreatedBy(v int64) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateCreatedBy() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UsageRequestCaptureShareUpsert) AddCreatedBy(v int64) *UsageRequestCaptureShareUpsert {
	u.Add(usagerequestcaptureshare.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UsageRequestCaptureShareUpsert) ClearCreatedBy() *UsageRequestCaptureShareUpsert {
	u.SetNull(usagerequestcaptureshare.FieldCreatedBy)
	return u
}

// SetLabel sets the "label" field.
func (u *UsageRequestCaptureShareUpsert) SetLabel(v string) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateLabel() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldLabel)
	return u
}

// ClearLabel clears the value of the "label" field.
func (u *UsageRequestCaptureShareUpsert) ClearLabel() *UsageRequestCaptureShareUpsert {
	u.SetNull(usagerequestcaptureshare.FieldLabel)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UsageRequestCaptureShareUpsert) SetExpiresAt(v time.Time) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateExpiresAt() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UsageRequestCaptureShareUpsert) ClearExpiresAt() *UsageRequestCaptureShareUpsert {
	u.SetNull(usagerequestcaptureshare.FieldExpiresAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *UsageRequestCaptureShareUpsert) SetRevokedAt(v time.Time) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateRevokedAt() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *UsageRequestCaptureShareUpsert) ClearRevokedAt() *UsageRequestCaptureShareUpsert {
	u.SetNull(usagerequestcaptureshare.FieldRevokedAt)
	return u
}

// SetViewCount sets the "view_count" field.
func (u *UsageRequestCaptureShareUpsert) SetViewCount(v int) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldViewCount, v)
	return u
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateViewCount() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldViewCount)
	return u
}

// AddViewCount adds v to the "view_count" field.
func (u *UsageRequestCaptureShareUpsert) AddViewCount(v int) *UsageRequestCaptureShareUpsert {
	u.Add(usagerequestcaptureshare.FieldViewCount, v)
	return u
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (u *UsageRequestCaptureShareUpsert) SetLastViewedAt(v time.Time) *UsageRequestCaptureShareUpsert {
	u.Set(usagerequestcaptureshare.FieldLastViewedAt, v)
	return u
}

// UpdateLastViewedAt sets the "last_viewed_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsert) UpdateLastViewedAt() *UsageRequestCaptureShareUpsert {
	u.SetExcluded(usagerequestcaptureshare.FieldLastViewedAt)
	return u
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (u *UsageRequestCaptureShareUpsert) ClearLastViewedAt() *UsageRequestCaptureShareUpsert {
	u.SetNull(usagerequestcaptureshare.FieldLastViewedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageRequestCaptureShare.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageRequestCaptureShareUpsertOne) UpdateNewValues() *UsageRequestCaptureShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagerequestcaptureshare.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageRequestCaptureShare.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageRequestCaptureShareUpsertOne) Ignore() *UsageRequestCaptureShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageRequestCaptureShareUpsertOne) DoNothing() *UsageRequestCaptureShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageRequestCaptureShareCreate.OnConflict
// documentation for more info.
func (u *UsageRequestCaptureShareUpsertOne) Update(set func(*UsageRequestCaptureShareUpsert)) *UsageRequestCaptureShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageRequestCaptureShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetShareID sets the "share_id" field.
func (u *UsageRequestCaptureShareUpsertOne) SetShareID(v string) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateShareID() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateShareID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *UsageRequestCaptureShareUpsertOne) SetRequestID(v string) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateRequestID() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsertOne) SetAPIKeyID(v int64) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsertOne) AddAPIKeyID(v int64) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateAPIKeyID() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsertOne) ClearAPIKeyID() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UsageRequestCaptureShareUpsertOne) SetCreatedBy(v int64) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UsageRequestCaptureShareUpsertOne) AddCreatedBy(v int64) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateCreatedBy() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UsageRequestCaptureShareUpsertOne) ClearCreatedBy() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearCreatedBy()
	})
}

// SetLabel sets the "label" field.
func (u *UsageRequestCaptureShareUpsertOne) SetLabel(v string) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateLabel() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateLabel()
	})
}

// ClearLabel clears the value of the "label" field.
func (u *UsageRequestCaptureShareUpsertOne) ClearLabel() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearLabel()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UsageRequestCaptureShareUpsertOne) SetExpiresAt(v time.Time) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateExpiresAt() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UsageRequestCaptureShareUpsertOne) ClearExpiresAt() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *UsageRequestCaptureShareUpsertOne) SetRevokedAt(v time.Time) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateRevokedAt() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *UsageRequestCaptureShareUpsertOne) ClearRevokedAt() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearRevokedAt()
	})
}

// SetViewCount sets the "view_count" field.
func (u *UsageRequestCaptureShareUpsertOne) SetViewCount(v int) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *UsageRequestCaptureShareUpsertOne) AddViewCount(v int) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateViewCount() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateViewCount()
	})
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (u *UsageRequestCaptureShareUpsertOne) SetLastViewedAt(v time.Time) *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetLastViewedAt(v)
	})
}

// UpdateLastViewedAt sets the "last_viewed_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertOne) UpdateLastViewedAt() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateLastViewedAt()
	})
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (u *UsageRequestCaptureShareUpsertOne) ClearLastViewedAt() *UsageRequestCaptureShareUpsertOne {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearLastViewedAt()
	})
}

// Exec executes the query.
func (u *UsageRequestCaptureShareUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageRequestCaptureShareCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageRequestCaptureShareUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageRequestCaptureShareUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageRequestCaptureShareUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageRequestCaptureShareCreateBulk is the builder for creating many UsageRequestCaptureShare entities in bulk.
type UsageRequestCaptureShareCreateBulk struct {
	config
	err      error
	builders []*UsageRequestCaptureShareCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageRequestCaptureShare entities in the database.
func (_c *UsageRequestCaptureShareCreateBulk) Save(ctx context.Context) ([]*UsageRequestCaptureShare, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageRequestCaptureShare, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageRequestCaptureShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageRequestCaptureShareCreateBulk) SaveX(ctx context.Context) []*UsageRequestCaptureShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageRequestCaptureShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageRequestCaptureShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageRequestCaptureShare.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageRequestCaptureShareUpsert) {
//			SetShareID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageRequestCaptureShareCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageRequestCaptureShareUpsertBulk {
	_c.conflict = opts
	return &UsageRequestCaptureShareUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageRequestCaptureShare.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageRequestCaptureShareCreateBulk) OnConflictColumns(columns ...string) *UsageRequestCaptureShareUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageRequestCaptureShareUpsertBulk{
		create: _c,
	}
}

// UsageRequestCaptureShareUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageRequestCaptureShare nodes.
type UsageRequestCaptureShareUpsertBulk struct {
	create *UsageRequestCaptureShareCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageRequestCaptureShare.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageRequestCaptureShareUpsertBulk) UpdateNewValues() *UsageRequestCaptureShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagerequestcaptureshare.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageRequestCaptureShare.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageRequestCaptureShareUpsertBulk) Ignore() *UsageRequestCaptureShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageRequestCaptureShareUpsertBulk) DoNothing() *UsageRequestCaptureShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageRequestCaptureShareCreateBulk.OnConflict
// documentation for more info.
func (u *UsageRequestCaptureShareUpsertBulk) Update(set func(*UsageRequestCaptureShareUpsert)) *UsageRequestCaptureShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageRequestCaptureShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetShareID sets the "share_id" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetShareID(v string) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateShareID() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateShareID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetRequestID(v string) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateRequestID() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetAPIKeyID(v int64) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsertBulk) AddAPIKeyID(v int64) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateAPIKeyID() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *UsageRequestCaptureShareUpsertBulk) ClearAPIKeyID() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetCreatedBy(v int64) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UsageRequestCaptureShareUpsertBulk) AddCreatedBy(v int64) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateCreatedBy() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UsageRequestCaptureShareUpsertBulk) ClearCreatedBy() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearCreatedBy()
	})
}

// SetLabel sets the "label" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetLabel(v string) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateLabel() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateLabel()
	})
}

// ClearLabel clears the value of the "label" field.
func (u *UsageRequestCaptureShareUpsertBulk) ClearLabel() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearLabel()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetExpiresAt(v time.Time) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateExpiresAt() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UsageRequestCaptureShareUpsertBulk) ClearExpiresAt() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetRevokedAt(v time.Time) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateRevokedAt() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *UsageRequestCaptureShareUpsertBulk) ClearRevokedAt() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearRevokedAt()
	})
}

// SetViewCount sets the "view_count" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetViewCount(v int) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *UsageRequestCaptureShareUpsertBulk) AddViewCount(v int) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateViewCount() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateViewCount()
	})
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (u *UsageRequestCaptureShareUpsertBulk) SetLastViewedAt(v time.Time) *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.SetLastViewedAt(v)
	})
}

// UpdateLastViewedAt sets the "last_viewed_at" field to the value that was provided on create.
func (u *UsageRequestCaptureShareUpsertBulk) UpdateLastViewedAt() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.UpdateLastViewedAt()
	})
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (u *UsageRequestCaptureShareUpsertBulk) ClearLastViewedAt() *UsageRequestCaptureShareUpsertBulk {
	return u.Update(func(s *UsageRequestCaptureShareUpsert) {
		s.ClearLastViewedAt()
	})
}

// Exec executes the query.
func (u *UsageRequestCaptureShareUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageRequestCaptureShareCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageRequestCaptureShareCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageRequestCaptureShareUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
