// Code generated by ent, DO NOT EDIT.

package usagerequestcapture

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usagerequestcapture type in the database.
	Label = "usage_request_capture"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldRequestBytes holds the string denoting the request_bytes field in the database.
	FieldRequestBytes = "request_bytes"
	// FieldResponseBytes holds the string denoting the response_bytes field in the database.
	FieldResponseBytes = "response_bytes"
	// FieldCompressedBytes holds the string denoting the compressed_bytes field in the database.
	FieldCompressedBytes = "compressed_bytes"
	// FieldTruncated holds the string denoting the truncated field in the database.
	FieldTruncated = "truncated"
	// FieldTruncateReason holds the string denoting the truncate_reason field in the database.
	FieldTruncateReason = "truncate_reason"
	// FieldCaptureSchemaVersion holds the string denoting the capture_schema_version field in the database.
	FieldCaptureSchemaVersion = "capture_schema_version"
	// FieldPayloadGzip holds the string denoting the payload_gzip field in the database.
	FieldPayloadGzip = "payload_gzip"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the usagerequestcapture in the database.
	Table = "usage_request_captures"
)

// Columns holds all SQL columns for usagerequestcapture fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldAPIKeyID,
	FieldUsageLogID,
	FieldUserID,
	FieldAccountID,
	FieldProvider,
	FieldModel,
	FieldEndpoint,
	FieldStream,
	FieldStatusCode,
	FieldDurationMs,
	FieldRequestBytes,
	FieldResponseBytes,
	FieldCompressedBytes,
	FieldTruncated,
	FieldTruncateReason,
	FieldCaptureSchemaVersion,
	FieldPayloadGzip,
	FieldCreatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultTruncated holds the default value on creation for the "truncated" field.
	DefaultTruncated bool
	// TruncateReasonValidator is a validator for the "truncate_reason" field. It is called by the builders before save.
	TruncateReasonValidator func(string) error
	// DefaultCaptureSchemaVersion holds the default value on creation for the "capture_schema_version" field.
	DefaultCaptureSchemaVersion int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageRequestCapture queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByRequestBytes orders the results by the request_bytes field.
func ByRequestBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBytes, opts...).ToFunc()
}

// ByResponseBytes orders the results by the response_bytes field.
func ByResponseBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBytes, opts...).ToFunc()
}

// ByCompressedBytes orders the results by the compressed_bytes field.
func ByCompressedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompressedBytes, opts...).ToFunc()
}

// ByTruncated orders the results by the truncated field.
func ByTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTruncated, opts...).ToFunc()
}

// ByTruncateReason orders the results by the truncate_reason field.
func ByTruncateReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTruncateReason, opts...).ToFunc()
}

// ByCaptureSchemaVersion orders the results by the capture_schema_version field.
func ByCaptureSchemaVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptureSchemaVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
