// Code generated by ent, DO NOT EDIT.

package usagerequestcapture

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldRequestID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldAPIKeyID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldUsageLogID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldAccountID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldProvider, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldModel, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldEndpoint, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldStream, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldDurationMs, v))
}

// RequestBytes applies equality check predicate on the "request_bytes" field. It's identical to RequestBytesEQ.
func RequestBytes(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldRequestBytes, v))
}

// ResponseBytes applies equality check predicate on the "response_bytes" field. It's identical to ResponseBytesEQ.
func ResponseBytes(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldResponseBytes, v))
}

// CompressedBytes applies equality check predicate on the "compressed_bytes" field. It's identical to CompressedBytesEQ.
func CompressedBytes(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldCompressedBytes, v))
}

// Truncated applies equality check predicate on the "truncated" field. It's identical to TruncatedEQ.
func Truncated(v bool) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldTruncated, v))
}

// TruncateReason applies equality check predicate on the "truncate_reason" field. It's identical to TruncateReasonEQ.
func TruncateReason(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldTruncateReason, v))
}

// CaptureSchemaVersion applies equality check predicate on the "capture_schema_version" field. It's identical to CaptureSchemaVersionEQ.
func CaptureSchemaVersion(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldCaptureSchemaVersion, v))
}

// PayloadGzip applies equality check predicate on the "payload_gzip" field. It's identical to PayloadGzipEQ.
func PayloadGzip(v []byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldPayloadGzip, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldExpiresAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContainsFold(FieldRequestID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotNull(FieldAPIKeyID))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotNull(FieldUsageLogID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotNull(FieldUserID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotNull(FieldAccountID))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContainsFold(FieldProvider, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContainsFold(FieldModel, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContainsFold(FieldEndpoint, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldStream, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldStatusCode, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldDurationMs, v))
}

// RequestBytesEQ applies the EQ predicate on the "request_bytes" field.
func RequestBytesEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldRequestBytes, v))
}

// RequestBytesNEQ applies the NEQ predicate on the "request_bytes" field.
func RequestBytesNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldRequestBytes, v))
}

// RequestBytesIn applies the In predicate on the "request_bytes" field.
func RequestBytesIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldRequestBytes, vs...))
}

// RequestBytesNotIn applies the NotIn predicate on the "request_bytes" field.
func RequestBytesNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldRequestBytes, vs...))
}

// RequestBytesGT applies the GT predicate on the "request_bytes" field.
func RequestBytesGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldRequestBytes, v))
}

// RequestBytesGTE applies the GTE predicate on the "request_bytes" field.
func RequestBytesGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldRequestBytes, v))
}

// RequestBytesLT applies the LT predicate on the "request_bytes" field.
func RequestBytesLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldRequestBytes, v))
}

// RequestBytesLTE applies the LTE predicate on the "request_bytes" field.
func RequestBytesLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldRequestBytes, v))
}

// ResponseBytesEQ applies the EQ predicate on the "response_bytes" field.
func ResponseBytesEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldResponseBytes, v))
}

// ResponseBytesNEQ applies the NEQ predicate on the "response_bytes" field.
func ResponseBytesNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldResponseBytes, v))
}

// ResponseBytesIn applies the In predicate on the "response_bytes" field.
func ResponseBytesIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldResponseBytes, vs...))
}

// ResponseBytesNotIn applies the NotIn predicate on the "response_bytes" field.
func ResponseBytesNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldResponseBytes, vs...))
}

// ResponseBytesGT applies the GT predicate on the "response_bytes" field.
func ResponseBytesGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldResponseBytes, v))
}

// ResponseBytesGTE applies the GTE predicate on the "response_bytes" field.
func ResponseBytesGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldResponseBytes, v))
}

// ResponseBytesLT applies the LT predicate on the "response_bytes" field.
func ResponseBytesLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldResponseBytes, v))
}

// ResponseBytesLTE applies the LTE predicate on the "response_bytes" field.
func ResponseBytesLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldResponseBytes, v))
}

// CompressedBytesEQ applies the EQ predicate on the "compressed_bytes" field.
func CompressedBytesEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldCompressedBytes, v))
}

// CompressedBytesNEQ applies the NEQ predicate on the "compressed_bytes" field.
func CompressedBytesNEQ(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldCompressedBytes, v))
}

// CompressedBytesIn applies the In predicate on the "compressed_bytes" field.
func CompressedBytesIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldCompressedBytes, vs...))
}

// CompressedBytesNotIn applies the NotIn predicate on the "compressed_bytes" field.
func CompressedBytesNotIn(vs ...int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldCompressedBytes, vs...))
}

// CompressedBytesGT applies the GT predicate on the "compressed_bytes" field.
func CompressedBytesGT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldCompressedBytes, v))
}

// CompressedBytesGTE applies the GTE predicate on the "compressed_bytes" field.
func CompressedBytesGTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldCompressedBytes, v))
}

// CompressedBytesLT applies the LT predicate on the "compressed_bytes" field.
func CompressedBytesLT(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldCompressedBytes, v))
}

// CompressedBytesLTE applies the LTE predicate on the "compressed_bytes" field.
func CompressedBytesLTE(v int64) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldCompressedBytes, v))
}

// TruncatedEQ applies the EQ predicate on the "truncated" field.
func TruncatedEQ(v bool) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldTruncated, v))
}

// TruncatedNEQ applies the NEQ predicate on the "truncated" field.
func TruncatedNEQ(v bool) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldTruncated, v))
}

// TruncateReasonEQ applies the EQ predicate on the "truncate_reason" field.
func TruncateReasonEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldTruncateReason, v))
}

// TruncateReasonNEQ applies the NEQ predicate on the "truncate_reason" field.
func TruncateReasonNEQ(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldTruncateReason, v))
}

// TruncateReasonIn applies the In predicate on the "truncate_reason" field.
func TruncateReasonIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldTruncateReason, vs...))
}

// TruncateReasonNotIn applies the NotIn predicate on the "truncate_reason" field.
func TruncateReasonNotIn(vs ...string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldTruncateReason, vs...))
}

// TruncateReasonGT applies the GT predicate on the "truncate_reason" field.
func TruncateReasonGT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldTruncateReason, v))
}

// TruncateReasonGTE applies the GTE predicate on the "truncate_reason" field.
func TruncateReasonGTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldTruncateReason, v))
}

// TruncateReasonLT applies the LT predicate on the "truncate_reason" field.
func TruncateReasonLT(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldTruncateReason, v))
}

// TruncateReasonLTE applies the LTE predicate on the "truncate_reason" field.
func TruncateReasonLTE(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldTruncateReason, v))
}

// TruncateReasonContains applies the Contains predicate on the "truncate_reason" field.
func TruncateReasonContains(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContains(FieldTruncateReason, v))
}

// TruncateReasonHasPrefix applies the HasPrefix predicate on the "truncate_reason" field.
func TruncateReasonHasPrefix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasPrefix(FieldTruncateReason, v))
}

// TruncateReasonHasSuffix applies the HasSuffix predicate on the "truncate_reason" field.
func TruncateReasonHasSuffix(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldHasSuffix(FieldTruncateReason, v))
}

// TruncateReasonIsNil applies the IsNil predicate on the "truncate_reason" field.
func TruncateReasonIsNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIsNull(FieldTruncateReason))
}

// TruncateReasonNotNil applies the NotNil predicate on the "truncate_reason" field.
func TruncateReasonNotNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotNull(FieldTruncateReason))
}

// TruncateReasonEqualFold applies the EqualFold predicate on the "truncate_reason" field.
func TruncateReasonEqualFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEqualFold(FieldTruncateReason, v))
}

// TruncateReasonContainsFold applies the ContainsFold predicate on the "truncate_reason" field.
func TruncateReasonContainsFold(v string) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldContainsFold(FieldTruncateReason, v))
}

// CaptureSchemaVersionEQ applies the EQ predicate on the "capture_schema_version" field.
func CaptureSchemaVersionEQ(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldCaptureSchemaVersion, v))
}

// CaptureSchemaVersionNEQ applies the NEQ predicate on the "capture_schema_version" field.
func CaptureSchemaVersionNEQ(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldCaptureSchemaVersion, v))
}

// CaptureSchemaVersionIn applies the In predicate on the "capture_schema_version" field.
func CaptureSchemaVersionIn(vs ...int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldCaptureSchemaVersion, vs...))
}

// CaptureSchemaVersionNotIn applies the NotIn predicate on the "capture_schema_version" field.
func CaptureSchemaVersionNotIn(vs ...int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldCaptureSchemaVersion, vs...))
}

// CaptureSchemaVersionGT applies the GT predicate on the "capture_schema_version" field.
func CaptureSchemaVersionGT(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldCaptureSchemaVersion, v))
}

// CaptureSchemaVersionGTE applies the GTE predicate on the "capture_schema_version" field.
func CaptureSchemaVersionGTE(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldCaptureSchemaVersion, v))
}

// CaptureSchemaVersionLT applies the LT predicate on the "capture_schema_version" field.
func CaptureSchemaVersionLT(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldCaptureSchemaVersion, v))
}

// CaptureSchemaVersionLTE applies the LTE predicate on the "capture_schema_version" field.
func CaptureSchemaVersionLTE(v int) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldCaptureSchemaVersion, v))
}

// PayloadGzipEQ applies the EQ predicate on the "payload_gzip" field.
func PayloadGzipEQ(v []byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldPayloadGzip, v))
}

// PayloadGzipNEQ applies the NEQ predicate on the "payload_gzip" field.
func PayloadGzipNEQ(v []byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldPayloadGzip, v))
}

// PayloadGzipIn applies the In predicate on the "payload_gzip" field.
func PayloadGzipIn(vs ...[]byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldPayloadGzip, vs...))
}

// PayloadGzipNotIn applies the NotIn predicate on the "payload_gzip" field.
func PayloadGzipNotIn(vs ...[]byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldPayloadGzip, vs...))
}

// PayloadGzipGT applies the GT predicate on the "payload_gzip" field.
func PayloadGzipGT(v []byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldPayloadGzip, v))
}

// PayloadGzipGTE applies the GTE predicate on the "payload_gzip" field.
func PayloadGzipGTE(v []byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldPayloadGzip, v))
}

// PayloadGzipLT applies the LT predicate on the "payload_gzip" field.
func PayloadGzipLT(v []byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldPayloadGzip, v))
}

// PayloadGzipLTE applies the LTE predicate on the "payload_gzip" field.
func PayloadGzipLTE(v []byte) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldPayloadGzip, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageRequestCapture) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageRequestCapture) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageRequestCapture) predicate.UsageRequestCapture {
	return predicate.UsageRequestCapture(sql.NotPredicates(p))
}
