// Code generated by ent, DO NOT EDIT.

package usagerequestcaptureshare

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldID, id))
}

// ShareID applies equality check predicate on the "share_id" field. It's identical to ShareIDEQ.
func ShareID(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldShareID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldRequestID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldAPIKeyID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldCreatedBy, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldRevokedAt, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldViewCount, v))
}

// LastViewedAt applies equality check predicate on the "last_viewed_at" field. It's identical to LastViewedAtEQ.
func LastViewedAt(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldLastViewedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldCreatedAt, v))
}

// ShareIDEQ applies the EQ predicate on the "share_id" field.
func ShareIDEQ(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldShareID, v))
}

// ShareIDNEQ applies the NEQ predicate on the "share_id" field.
func ShareIDNEQ(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldShareID, v))
}

// ShareIDIn applies the In predicate on the "share_id" field.
func ShareIDIn(vs ...string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldShareID, vs...))
}

// ShareIDNotIn applies the NotIn predicate on the "share_id" field.
func ShareIDNotIn(vs ...string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldShareID, vs...))
}

// ShareIDGT applies the GT predicate on the "share_id" field.
func ShareIDGT(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldShareID, v))
}

// ShareIDGTE applies the GTE predicate on the "share_id" field.
func ShareIDGTE(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldShareID, v))
}

// ShareIDLT applies the LT predicate on the "share_id" field.
func ShareIDLT(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldShareID, v))
}

// ShareIDLTE applies the LTE predicate on the "share_id" field.
func ShareIDLTE(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldShareID, v))
}

// ShareIDContains applies the Contains predicate on the "share_id" field.
func ShareIDContains(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldContains(FieldShareID, v))
}

// ShareIDHasPrefix applies the HasPrefix predicate on the "share_id" field.
func ShareIDHasPrefix(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldHasPrefix(FieldShareID, v))
}

// ShareIDHasSuffix applies the HasSuffix predicate on the "share_id" field.
func ShareIDHasSuffix(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldHasSuffix(FieldShareID, v))
}

// ShareIDEqualFold applies the EqualFold predicate on the "share_id" field.
func ShareIDEqualFold(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEqualFold(FieldShareID, v))
}

// ShareIDContainsFold applies the ContainsFold predicate on the "share_id" field.
func ShareIDContainsFold(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldContainsFold(FieldShareID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldContainsFold(FieldRequestID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotNull(FieldAPIKeyID))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotNull(FieldCreatedBy))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldContainsFold(FieldLabel, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotNull(FieldExpiresAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotNull(FieldRevokedAt))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v int) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldViewCount, v))
}

// LastViewedAtEQ applies the EQ predicate on the "last_viewed_at" field.
func LastViewedAtEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldLastViewedAt, v))
}

// LastViewedAtNEQ applies the NEQ predicate on the "last_viewed_at" field.
func LastViewedAtNEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldLastViewedAt, v))
}

// LastViewedAtIn applies the In predicate on the "last_viewed_at" field.
func LastViewedAtIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldLastViewedAt, vs...))
}

// LastViewedAtNotIn applies the NotIn predicate on the "last_viewed_at" field.
func LastViewedAtNotIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldLastViewedAt, vs...))
}

// LastViewedAtGT applies the GT predicate on the "last_viewed_at" field.
func LastViewedAtGT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldLastViewedAt, v))
}

// LastViewedAtGTE applies the GTE predicate on the "last_viewed_at" field.
func LastViewedAtGTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldLastViewedAt, v))
}

// LastViewedAtLT applies the LT predicate on the "last_viewed_at" field.
func LastViewedAtLT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldLastViewedAt, v))
}

// LastViewedAtLTE applies the LTE predicate on the "last_viewed_at" field.
func LastViewedAtLTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldLastViewedAt, v))
}

// LastViewedAtIsNil applies the IsNil predicate on the "last_viewed_at" field.
func LastViewedAtIsNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIsNull(FieldLastViewedAt))
}

// LastViewedAtNotNil applies the NotNil predicate on the "last_viewed_at" field.
func LastViewedAtNotNil() predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotNull(FieldLastViewedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageRequestCaptureShare) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageRequestCaptureShare) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageRequestCaptureShare) predicate.UsageRequestCaptureShare {
	return predicate.UsageRequestCaptureShare(sql.NotPredicates(p))
}
